# Generated by Django 5.2.1 on 2025-05-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rankings", "0002_evaluationcategory_alter_brand_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["current_rank", "name"],
                "verbose_name": "브랜드",
                "verbose_name_plural": "브랜드 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="evaluationcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "평가 카테고리",
                "verbose_name_plural": "평가 카테고리 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="evaluationitem",
            options={
                "ordering": ["category__name", "name"],
                "verbose_name": "평가 항목",
                "verbose_name_plural": "평가 항목 목록",
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="current_rank",
            field=models.IntegerField(blank=True, null=True, verbose_name="현재 순위"),
        ),
        migrations.AddField(
            model_name="brand",
            name="last_calculated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 순위 계산일"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="previous_rank",
            field=models.IntegerField(blank=True, null=True, verbose_name="지난 순위"),
        ),
        migrations.AddField(
            model_name="brand",
            name="total_score",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="현재 종합 점수"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="last_activity",
            field=models.TextField(
                blank=True, null=True, verbose_name="마지막 활동/이슈"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="brand_logos/", verbose_name="로고"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="브랜드명"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcategory",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="카테고리명"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationitem",
            name="name",
            field=models.CharField(max_length=100, verbose_name="평가 항목명"),
        ),
        migrations.AlterField(
            model_name="evaluationitem",
            name="weight",
            field=models.FloatField(
                default=0.0,
                help_text="예: 0.2는 20%를 의미합니다.",
                verbose_name="가중치",
            ),
        ),
        migrations.CreateModel(
            name="BrandEvaluationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="점수"),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="평가일"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="rankings.brand",
                        verbose_name="브랜드",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="rankings.evaluationitem",
                        verbose_name="평가 항목",
                    ),
                ),
            ],
            options={
                "verbose_name": "브랜드 평가 점수",
                "verbose_name_plural": "브랜드 평가 점수 목록",
                "ordering": ["brand__name", "item__category__name", "item__name"],
                "unique_together": {("brand", "item")},
            },
        ),
    ]
